import NavBar from "@/components/NavBar";
import Foote from "../components/Fotter";

import "./globals.css";

export const metadata = {
  title: "FreeSpace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <NavBar />
      <div className="main">
         {children}
        </div>
        <Foote />
      </body>
    </html>
  );
}
